DROP TRIGGER IF EXISTS Q1;
DELIMITER $$
CREATE TRIGGER Q1
BEFORE INSERT ON `group` FOR EACH ROW
BEGIN
	IF NEW.CreateDate > now()
    OR NEW.CreateDate < date_sub(now(), INTERVAL 1 YEAR)
    THEN SIGNAL SQLSTATE '12345' SET MESSAGE_TEXT = 'Ngay khong hop le !';
    END IF;
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS Q2;
DELIMITER $$
CREATE TRIGGER Q2
BEFORE INSERT ON `account` FOR EACH ROW
BEGIN
	IF NEW.DepartmentID = (SELECT DepartmentID FROM department WHERE DepartmentName = 'SALE')
    THEN SIGNAL SQLSTATE '12345' SET MESSAGE_TEXT = 'Department "Sale" cannot add more user';
    END IF;
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS Q3;
DELIMITER $$
CREATE TRIGGER Q3
BEFORE INSERT ON groupaccount FOR EACH ROW
BEGIN
	IF (SELECT count(1) FROM groupaccount WHERE GroupID = NEW.GroupID) >= 5
    THEN SIGNAL SQLSTATE '12345' SET MESSAGE_TEXT = '1 group có nhiều nhất là 5 user';
    END IF;
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS Q4;
DELIMITER $$
CREATE TRIGGER Q4
BEFORE INSERT ON examquestion FOR EACH ROW
BEGIN
	IF (SELECT count(1) FROM examquestion WHERE ExamID = NEW.ExamID) >= 10
    THEN SIGNAL SQLSTATE '12345' SET MESSAGE_TEXT = '1 EXAM có nhiều nhất là 10 QUIZ';
    END IF;
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS Q5;
DELIMITER $$
CREATE TRIGGER Q5
BEFORE DELETE ON `account` FOR EACH ROW
BEGIN
	IF OLD.Email = 'chutich@gmail.com'
    THEN SIGNAL SQLSTATE '12345' SET MESSAGE_TEXT = 'đây là tài khoản admin';
    END IF;
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS Q6;
DELIMITER $$
CREATE TRIGGER Q6
BEFORE INSERT ON `account` FOR EACH ROW
BEGIN
	IF NEW.DepartmentID IS NULL
    THEN SET NEW.DepartmentID = (SELECT DepartmentID FROM department WHERE DepartmentName = 'PHONG CHO');
    END IF;
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS Q7;
DELIMITER $$
CREATE TRIGGER Q7
BEFORE INSERT ON answer FOR EACH ROW
BEGIN
	IF (SELECT count(1) FROM answer WHERE QuestionID = NEW.QuestionID) >= 4
    THEN SIGNAL SQLSTATE '12345' SET MESSAGE_TEXT = 'tối đa 4 answers cho mỗi question';
    END IF;
    IF (SELECT count(1) FROM answer WHERE QuestionID = NEW.QuestionID AND isCorrect = TRUE) >= 2
    AND NEW.isCorrect = TRUE
    THEN SIGNAL SQLSTATE '12345' SET MESSAGE_TEXT = 'tối đa 2 đáp án đúng';
    END IF; 
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS Q8;
DELIMITER $$
CREATE TRIGGER Q8
BEFORE INSERT ON `account` FOR EACH ROW
BEGIN
	IF NEW.GENDER NOT IN ('M','F','U') THEN
		CASE
			WHEN NEW.GENDER = 'NAM' THEN SET NEW.GENDER = 'M';
			WHEN NEW.GENDER = 'NU' THEN SET NEW.GENDER = 'F';
            WHEN NEW.GENDER = 'CHUA XAC DINH' THEN SET NEW.GENDER = 'U';
            ELSE SIGNAL SQLSTATE '12345' SET MESSAGE_TEXT = 'DU LIEU KO HOP LE';
        END CASE;
    END IF;
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS Q9;
DELIMITER $$
CREATE TRIGGER Q9
BEFORE DELETE ON exam FOR EACH ROW
BEGIN
	IF OLD.CreateDate > date_sub(now(), INTERVAL 2 DAY)
    THEN SIGNAL SQLSTATE '12345' SET MESSAGE_TEXT = 'KO DC XOA';		
    END IF;
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS Q10;
DELIMITER $$
CREATE TRIGGER Q10
BEFORE DELETE ON question FOR EACH ROW
BEGIN
	IF OLD.QuestionID IN (SELECT QuestionID FROM examquestion)
    THEN SIGNAL SQLSTATE '12345' SET MESSAGE_TEXT = 'KO DC';		
    END IF;
END$$
DELIMITER ;

SELECT *
FROM department LEFT JOIN `account` ON department.DepartmentID = account.DepartmentID
GROUP BY department.DepartmentID